version: '3'

services:
 backend:
  build: ./backend
  ports:
   - 8080:8080
  container_name: backend

 frontend:
  build: ./frontend
  ports:
   - 5000:5000
  container_name: frontend

 watchtower:
  image: containrrr/watchtower
  environment:
   - WATCHTOWER_POLL_INTERVAL=10 # Poll every 60 seconds
   - WATCHTOWER_MONITOR_ONLY=true
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  container_name: watchtower
